# Generated by Django 3.2.5 on 2021-08-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=25)),
                ('origin', models.CharField(default='', max_length=20)),
                ('last_update', models.DateTimeField(verbose_name='last update')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('measure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.measure')),
            ],
            bases=('polls.measure',),
        ),
    ]
